lwc-assignments
Vikramsinghyadav/Developer pull request #2
Opened 2024-08-09 11:20 UTC by Vikramsinghyadav

2024-09-03 11:40 UTC, Mr-pm-tv requested changes
I have reviewd few classes and cmp, review all the requested changes, and make sure same kind of mistakes should not be there in any other class/cmp

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.html
> +       <!-- Record form for Contact
remove unwanted code lines

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.html
> +        <lightning-layout></lightning-layout>
why this blank layout?

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js
> +    @track fields=[];
do we need `@track` here?

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js
> +    @api recordId;
Is this component is on Designation record page?

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js
> +           // console.log('fields'+JSON.stringify(this.fields));
remove log

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js
> +               // console.log('Processing element: ', element);
remove log

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js
> +                           // console.log('fields ka data'+JSON.stringify(this.fieldsetdata));
remove log

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js
> +                                   // console.log('Processing record: ', record);
remove commented code

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js
> +                           // console.log('Sum of Feedback_Rating_Count__c: ' + sum);
remove commented code

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js
> +               // console.log(this.contactId);
remove commented code

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js
> +               // console.error('Error fetching contact ID:', error);
remove commented code

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js
> +                this.contactId = null;
this will be default null, you can explore on error handling part and find the best way to handle such errors

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js-meta.xml
find a way so that we can specify this cmp for a particular object oly

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/lwc/mVPNomineeContributions/mVPNomineeContributions.html
fix the indentation, use pritter or HTML formator to fix this

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/lwc/mVPNomineeContributions/mVPNomineeContributions.js
> +    @api firstName="this is demo firstName";
why this hardcoded?

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/lwc/mVPNomineeContributions/mVPNomineeContributions.js
> +               // console.log('Wrapper data of contributions:'+JSON.stringify(data));
remove log

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/lwc/mVPNomineeContributions/mVPNomineeContributions.js
> +               // console.log('this ois cons=tribuyion'+this.contributionids);
remove unwanted comment

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/lwc/mVPNomineeContributions/mVPNomineeContributions.js
> +                //console.error('Error fetching contact ID:', error);
remove unwanted comment

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/lwc/mVPNomineeContributions/mVPNomineeContributions.js
> +               // console.log('feedback set1 '+JSON.stringify(this.feedbackFields));
remove unwanted comment

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/classes/FieldSetController.cls
> +        System.debug('object '+objectName);
remove debug

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/classes/FieldSetController.cls
> +        Schema.FieldSet fieldSetObj = Schema.getGlobalDescribe().get(objectName).getDescribe().fieldSets.getMap().get(fieldSetName);
what if fieldSetName is blank?

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/classes/FieldSetController.cls
> +        return [select Feedback_Rating_Count__c from Contact where Feedback_Rating_Count__c != 0];
it will return multiple results from multiple contacts where this condition matched

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/lwc/mVPNomineeContributions/mVPNomineeContributions.js
> +            this.horizontalFields = data;
what if data comes as blank string?

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/classes/FeedbackController.cls
> +        FeedbackList=[select id,Nominator__c,Generosity__c,Leadership__c,Expertise__c,Advocacy__c,Name,RecordTypeId from Feedback__c where RecordTypeId = '012NS000000ntwPYAQ'];
hard coded id will not work in our case

2024-09-03 11:40 UTC, Mr-pm-tv commented on force-app/main/default/classes/FeedbackController.cls
> +        FeedbackList=[select id,Date__c,Nominator__c,Nominator__r.Email,Generosity__c,Leadership__c,Expertise__c,Advocacy__c,Name,RecordTypeId from Feedback__c where RecordTypeId = '012NS000000nvMxYA
remove hard-coded id and find a way to get it dynamically

2024-09-06 04:07 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js
> +    @api recordId;
Yes

2024-09-06 07:59 UTC, Vikramsinghyadav commented on force-app/main/default/classes/FieldSetController.cls
> +        Schema.FieldSet fieldSetObj = Schema.getGlobalDescribe().get(objectName).getDescribe().fieldSets.getMap().get(fieldSetName);
applied null check

2024-09-06 07:59 UTC, Vikramsinghyadav commented on force-app/main/default/classes/FieldSetController.cls
> +        return [select Feedback_Rating_Count__c from Contact where Feedback_Rating_Count__c != 0];
applied filter based on contactid

2024-09-06 08:03 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeContributions/mVPNomineeContributions.js
> +            this.horizontalFields = data;
applied null check

2024-09-06 08:07 UTC, Vikramsinghyadav commented on force-app/main/default/classes/FeedbackController.cls
> +        FeedbackList=[select id,Date__c,Nominator__c,Nominator__r.Email,Generosity__c,Leadership__c,Expertise__c,Advocacy__c,Name,RecordTypeId from Feedback__c where RecordTypeId = '012NS000000nvMxYA
removed hard coded

2024-09-06 08:07 UTC, Vikramsinghyadav commented on force-app/main/default/classes/FieldSetController.cls
> +        System.debug('object '+objectName);
removed

2024-09-06 08:08 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.html
> +       <!-- Record form for Contact
REMOVED

2024-09-06 08:08 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.html
> +        <lightning-layout></lightning-layout>
removed

2024-09-06 08:09 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js
> +    @track fields=[];
no beacues it is by default track

2024-09-06 08:09 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js
> +           // console.log('fields'+JSON.stringify(this.fields));
remove

2024-09-06 08:09 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js
> +               // console.log('Processing element: ', element);
removed

2024-09-06 08:09 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js
> +                           // console.log('fields ka data'+JSON.stringify(this.fieldsetdata));
removed

2024-09-06 08:10 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js
> +                           // console.log('Sum of Feedback_Rating_Count__c: ' + sum);
removed

2024-09-06 08:10 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js
> +                                   // console.log('Processing record: ', record);
removed

2024-09-06 08:10 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js
> +               // console.log(this.contactId);
removed

2024-09-06 08:10 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js
> +               // console.error('Error fetching contact ID:', error);
removed

2024-09-06 08:12 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js
> +                this.contactId = null;
added console.error

2024-09-06 08:15 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeContributions/mVPNomineeContributions.html
done

2024-09-06 08:16 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeContributions/mVPNomineeContributions.js
> +    @api firstName="this is demo firstName";
removed

2024-09-06 08:16 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeContributions/mVPNomineeContributions.js
> +               // console.log('Wrapper data of contributions:'+JSON.stringify(data));
removed

2024-09-06 08:16 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeContributions/mVPNomineeContributions.js
> +               // console.log('this ois cons=tribuyion'+this.contributionids);
removed

2024-09-06 08:16 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeContributions/mVPNomineeContributions.js
> +                //console.error('Error fetching contact ID:', error);
removed

2024-09-06 08:16 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeContributions/mVPNomineeContributions.js
> +               // console.log('feedback set1 '+JSON.stringify(this.feedbackFields));
removed

2024-09-06 08:17 UTC, Vikramsinghyadav commented on force-app/main/default/classes/FeedbackController.cls
> +        FeedbackList=[select id,Nominator__c,Generosity__c,Leadership__c,Expertise__c,Advocacy__c,Name,RecordTypeId from Feedback__c where RecordTypeId = '012NS000000ntwPYAQ'];
fixed

2024-09-06 08:17 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js-meta.xml
did't get it

2024-09-09 07:23 UTC, Mr-pm-tv requested changes
Do the required changes

2024-09-09 07:23 UTC, Mr-pm-tv commented on force-app/main/default/classes/FieldSetController.cls
> +        if(fieldSetName==null || fieldSetName==''){
for String, It's always best to use, String.isBlank() method to check null or empty strings

2024-09-09 07:23 UTC, Mr-pm-tv commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js-meta.xml
> +        <targetConfig targets="lightning__HomePage,lightning__RecordPage">
Have you been able to limit this cmp to the Designation object only? if not tried, try that there is a config available that you can use

2024-09-09 07:23 UTC, Mr-pm-tv commented on force-app/main/default/classes/DesignationController.cls
> +    @AuraEnabled(cacheable=true)
always try to write readable code, and add good spacing for good readability.

2024-09-09 07:23 UTC, Mr-pm-tv commented on force-app/main/default/classes/DesignationController.cls
> +                conList2.add(con);
for add this value can we not minimize the line and declaration of variable by just get the value (list) and adding the value (element) in list directly in single line.
ping me for any doubt

2024-09-09 07:23 UTC, Mr-pm-tv commented on force-app/main/default/classes/DesignationController.cls
> +                conMapWithYear.put(yearValue,conList2);
try to minimize the lines here

2024-09-09 07:23 UTC, Mr-pm-tv commented on force-app/main/default/classes/FeedbackController.cls
> +        List<RecordType> recTypeList = [SELECT Id, DeveloperName FROM RecordType WHERE SObjectType = 'Feedback__c' AND DeveloperName = :recordTypeName
there is another way of getting the record type id in apex, look for available option, it will reduce on SOQL

2024-09-09 08:55 UTC, Vikramsinghyadav commented on force-app/main/default/classes/DesignationController.cls
> +    @AuraEnabled(cacheable=true)
added good spacing

2024-09-09 08:55 UTC, Vikramsinghyadav commented on force-app/main/default/classes/DesignationController.cls
> +                conList2.add(con);
Converted into single line code

2024-09-09 08:56 UTC, Vikramsinghyadav commented on force-app/main/default/classes/DesignationController.cls
> +                conMapWithYear.put(yearValue,conList2);
converted into single line

2024-09-09 09:02 UTC, Vikramsinghyadav commented on force-app/main/default/classes/FeedbackController.cls
> +        List<RecordType> recTypeList = [SELECT Id, DeveloperName FROM RecordType WHERE SObjectType = 'Feedback__c' AND DeveloperName = :recordTypeName
used standard way of getting recordTypeId 
Map<String, Schema.RecordTypeInfo> recordTypeInfoMap = 
        Schema.SObjectType.Feedback__c.getRecordTypeInfosByDeveloperName();

2024-09-09 09:02 UTC, Vikramsinghyadav commented on force-app/main/default/classes/FieldSetController.cls
> +        if(fieldSetName==null || fieldSetName==''){
change done

2024-09-09 09:31 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js-meta.xml
> +        <targetConfig targets="lightning__HomePage,lightning__RecordPage">
done

2024-09-09 09:32 UTC, Vikramsinghyadav commented on force-app/main/default/lwc/mVPNomineeBasicInfo/mVPNomineeBasicInfo.js-meta.xml
done https://www.apexhours.com/use-component-in-salesforce-targets/#:~:text=Summary-,Use%20LWC%20in%20Lightning%20App%20Builder,-There%20are%20a

2024-09-09 10:34 UTC, Mr-pm-tv approved these changes

2024-09-09 10:35 UTC, merged